=== zanetatrosk/SQL-assignments/semestralni-prace/sproject_sql.dtd
<!ELEMENT sproject_sql (course, author, content)>
   <!ELEMENT course (cname, code, semester, seminar)>
   <!ELEMENT author (aname, uname, email)>
   <!ELEMENT content (declaration, title, description,  data_model, filling_rel, filling_obj, queries, queries_cover, proc_objects, script, conclussions, references)>
   <!ELEMENT description (title, (title2, (para, comment?)+)+,                                                title2,  (para, comment?)+)>
   <!ELEMENT data_model (title, dm_picture?, comment?,                                                  title2, (para, comment?)+, title2, (para, comment?)+, title2, (para, comment?)+)>
   <!ELEMENT filling_rel (title, (para, comment?)+)>
   <!ELEMENT filling_obj (title, (para, comment?)+)>
   <!ELEMENT queries (title, comment, query+)>
   <!ELEMENT queries_cover (query_cat+)>
   <!ELEMENT proc_objects (title, proc_object+)>
   <!ELEMENT conclussions (title, (para, comment?)+)>
   <!ELEMENT references (title, (para, comment?)+)>
   <!ELEMENT query (title2, (para, comment?)+, title3, title4, sql, comment?,			title4, ex_plan, comment?, title4, sql_result, comment?, title4, (para, comment?)+,		title4, (para, comment?)+, title3, title4, sql, comment?, title4, ex_plan, comment?,		title4, sql_result, comment?, title4, (para, comment?)+, title4, (para, comment?)+,		title3, title4, sql, comment?, title4, ex_plan, comment?, title4, sql_result, comment?,		title4, (para, comment?)+, title4, (para, comment?)+)>
   <!ATTLIST query query_id CDATA #REQUIRED>
   <!ELEMENT proc_object (title3, (para, comment?)+, title4, para?, proc_sql?, comment?,		title4, (para, proc_log?, comment?)+, title4, para?, proc_log?, comment?, title4, (para, comment?)+,	title4, (para, comment?)+)>
  <!ELEMENT script (title, (para, comment?)+)>
  <!ELEMENT cname (#PCDATA)>
  <!ELEMENT code (#PCDATA)>
  <!ELEMENT semester (#PCDATA)>
  <!ELEMENT seminar (#PCDATA)>
  <!ELEMENT aname (#PCDATA)>
  <!ELEMENT uname (#PCDATA)>
  <!ELEMENT email (#PCDATA)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT title2 (#PCDATA)>
  <!ELEMENT title3 (#PCDATA)>
  <!ELEMENT title4 (#PCDATA)>
  <!ELEMENT declaration (#PCDATA)>
  <!ELEMENT para (#PCDATA | link)*>
  <!ELEMENT comment (para)*>
  <!ELEMENT dm_picture (mediaobject)>
  <!ELEMENT query_cat (cat_id, cat_link, cat_description)>
  <!ELEMENT cat_id (#PCDATA )>
  <!ELEMENT cat_description (#PCDATA )>
  <!ELEMENT cat_link (link+)>

  <!ELEMENT entry (#PCDATA )>
  <!ELEMENT link (#PCDATA)>
  <!ATTLIST link  url CDATA #REQUIRED>
  <!ELEMENT sql (#PCDATA | link|dm_picture)*>
  <!ELEMENT ex_plan (#PCDATA | link)*>
  <!ELEMENT sql_result (#PCDATA | link)*>
  <!ELEMENT proc_sql (#PCDATA | link)*>
  <!ELEMENT proc_log (#PCDATA | link)*>
  <!ELEMENT mediaobject (imageobject)*>
  <!ELEMENT imageobject (imagedata)>
  <!ELEMENT imagedata EMPTY>
  <!ATTLIST imagedata fileref CDATA #REQUIRED>

=== zanetatrosk/SQL-assignments/semestralni-prace/main.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="sproject_sql_html.xsl"?>
<!--<!DOCTYPE sproject_sql PUBLIC "-//XMLmind//DTD Sproject_sql//EN" "http://users.fit.cvut.cz/~halaska/BI-SQL/semestralka/sprojekt/sproject_sql.dtd"> -->
<!DOCTYPE sproject_sql PUBLIC "-//XMLmind//DTD Sproject_sql//EN"
"sproject_sql.dtd">
<sproject_sql>
  <course>
    <cname>Jazyk SQL</cname>

    <code>BI-SQL</code>

    <semester>letní semestr 2013/2014</semester>

    <seminar>den a čas vašeho cvičení</seminar>
  </course>

  <author>
    <aname>vaše jméno</aname>

    <uname>vaše uživatelské jméno</uname>

    <email>váš email</email>
  </author>

  <content>
    <declaration>Prohlašuji, že jsem svou semestrální práci vypracoval samostatně. Všechny zdroje, ze kterých jsem
    čerpal, jsou uvedeny v části Odkazy.</declaration>

    <title>Název vaší semestrální práce</title>

    <description>
      <title>Popis</title>

      <title2>Charakteristika projektu</title2>

      <para>Stručná slovní charakteristika vašeho projektu (několik odstavců), kde popíšete "realitu", kterou budete ve
      vaší semestrálce databázově modelovat. Výhodným je navázat na semestrální práci bakalářského předmětu DBS.</para>
<para>Stručná slovní charakteristika rozšíření schématu o hierarchickou strukturu, umožňující rekurzivní dotazování</para>
      <comment><para>K O M E N T Á Ř E 

Tohle je komentář k 1. odstavci popisu semestrální práce.
           Komentář zobrazuje text tak, jak jej napíšete, zachovává formátování.

Zobrazení komentářů si můžete VYPNOUT 
   - v menu XML Mind Editoru View -&gt;   Hide comments
   - při html zobrazení tlačítkem "Vypnout/zapnout zobrazeni komentaru" přímo na html stránce.

Komentář můžete používat k vlastním poznámkám k částem práce, dále jej může využít váš cvičící k tomu, 
aby připojil svoje hodnocení k jednotlivým částem práce.

Komentovat lze samostatně:
           jednotlivé odstavce textů v částech Popis, Datové schéma, Skripty, Závěr, Odkazy 
           případný obrázek datového schématu
           jednotlivé SQL příkazy
           tabulku pokrytí kategorií SQL příkazů
          popis procedurálního rozšíření
          jednotlivé procedurální moduly, jejich implementaci a testování

Další informace o semestrální práci, struktuře, požadavcích a termínech jsou uvedeny 
formou komentářů přímo v tomto dokumentu.</para></comment>

      <title2>Popis návrhu procedurálního rozšíření</title2>

      <para>Textová specifikace procedurálního rozšíření, která bude podkladem pro doplnění relačního schématu o objekty
      procedurálniho typu (package tvořící API rozhraní bussiness logiky systému, pracujícího nad Vaším úložištěm
      (podporogramy, triggery):</para>

      <para>- povinnou součástí práce je modul pro vygenerování velkého množství pseudonáhodných testovacích dat</para>

      <para>- například realizujte kontrolu dodatečně formulovaného složitějšího integritního omezení pomocí
      databázových triggerů, které volaji uložené databázové procedury a funkce</para>

      <para>- například dopňte do schématu tabulku/tabulky s odvozenými hodnotami a pomocí procedurálních DB objektů
      zajistí jednorázové přepočítání odvozených hodnot z prvotních údajů</para>

      <para>- například realizujte kontrolu dodatečně formulovaného složitějšího integritního omezení pomocí
      databázových triggerů, které volaji uložené databázové procedury a funkce</para>

      <comment><para>S T R U K T U R A   S E M E S T R Á L N Í  P R Á C E 

Semestrálka má tyto části: 
1. hlavička (údaje o vás a o čase cvičení, prohlášení o autorství, název práce) 

2. popis 
   2.1 stručná slovní charakteristika vašeho projektu (několik odstavců), kde popíšete "realitu", 
          kterou budete ve vaší semestrálce databázově modelovat. 
          Výhodným je navázat na semestrální práce předmětu BI-DBS. 
   2.2. textová specifikace procedurálního rozšíření, která bude podkladem pro doplnění relačního schématu 
          o objekty procedurálniho typu (package tvořící API rozhraní bussiness logiky systému, 
          pracujícího nad Vaším úložištěm (podporogramy, triggery):
         *například realizujte kontrolu dodatečně formulovaného složitějšího integritního omezení pomocí 
           databázových triggerů, které volaji uložené databázové procedury a funkce,
        *například dopňte do schématu tabulku/tabulky s odvozenými hodnotami a pomocí procedurálních 
          DB objektů zajistí jednorázové přepočítání odvozených hodnot z prvotních údajů,
        *například zevrubně prozkoumejte datové schéma svého úložiště a z výskytu smyček ve schématu 
          vytypuje případné zdroje nekonzistencí, formulujte integritní omezení a zrealizuje jeho procedurální kontroly, 
         které budou vzniku těchto potenciálních datových nekonzistencí účinně bránit.
         *napríklad něco podobného.
   2.3.
3. datové schéma úložiště
   3.1 Obrázek relačního schématu (převzato z předmětu DBS) 
   3.2 Diskuse k datovému schématu zahrnuje výčet integritních omezení, které nebylo možné zahrnout do obrázku. 
       Jsou-li ve schématu smyčky, diskutujte, zda smyčka je potenciálním zdrojem datové nekonzistence
   3.3. SQL script pro vytvoření relačního db schématu

4. PLSQL modul, který automaticky naplní tabulky schématu větším množstvím konzistentních dat. 
    V modulu budou vedle příkazů "Insert ... Values" také použity příkazy "Insert ... Select" pro naplnění tabulek, 
    které budou obrazem typu vztahu M:N. Vložíme tak do tabulky výsledek spojení (JOIN) tabulek, 
    které jsou obrazem účastníků typu vztahu ("vztahových" tabulek) a dle potřeby také Update a Delete. 

5. deset databázových dotazů, které předjímají použití SQL v celém rozsahu jeho výrazových prostředků (z původních 25 dotazů vyberete ty reprezentativní)
   Pro každý dotaz:
   5.1 formulace v přirozeném jazyku 
   5.2 první verze 
        5.2.1. formulace v relačním SQL
        5.2.1. exekuční plán
        5.2.2. odezva 
        5.2.3. diskuse, ve které bude konstatováno, že odpověď na dotaz odpovídá očekávání autora dotazu v přirozeném jazyku 
        5.2.4. diskuse k efektivnosti exekučního plánu, ze které vyplyne změna exekučního plánu:
              * přidání indexů na sloupci, podle kterých se dotazuje a spojuje
              * dotaz lze formulovat syntakticky jinak a tudíž s jiným (lepším/horším) plánem provedení
              * změny vstupů pro optimalizátor, například přidáním indexů, přidáním materializovaných  pohledů, sběrem podrobnějších statistik
        5.2.5. Případné přidání vytipovaných indexů a zopakování první verze dotazu, do protokolu semestrálky pak přijde nový exekuční plán    
   5.3 druhá verze 
       5.3.1. formulace v relačním SQL
        5.3.2. exekuční plán
        5.3.3. odezva 
        5.3.3. diskuse, ve které bude konstatováno, že odpověď na dotaz odpovídá očekávání autora dotazu v přirozeném jazyku 
        5.3.4. diskuse porovnávající efektivnost obou dotazů

6. tabulka pokrytí požadovaných kategorií složitosti dotazů

7. procedurální rozšíření 
   Pro každý procedurální objekt:
   7.1. specifikace
   7.2. zdrojový text
   7.3. slovní specifikace struktury testu pro ověření fukčnosti o n krocích
        n-tý krok testu:
        - podívám se na současný stav relevantního fragmentu dat před testem
        - provedu pokus o provedení toho a toho ukonu, po provedeni očekávám, že v databázi nastanou ty a ty změny/pokus 
          bude odmitnut z toho a toho důvodu
        - pro ověření se podívám na stav relevantního fragmentu dat po akci,
   7.4 záznam (log) výstupu z proběhlého testu
   7.5 diskuse k výsledku testu a případnému ladění
   7.6 konstatování, že test ověřil správnou funkčnost

10. Celkový SQL script, obsahující zdrojové texty všech bodů 
   
10. Závěr

11. Odkazy na použité zdroje informací</para></comment>

      <comment><para>T E C H N O L O G I E   A  N Á S T R O J E   
   Semestrální práci odevzdáte ve formě XML dokumentu, který nahrajete do vašeho projektového adresáře na
   serveru service.felk.cvut.cz. Do tohoto adresáře umístíte také všechny zdrojové souboru a obrázek datového schématu.


UMÍSTĚNÍ PRÁCE:
   https://webdev.fit.cvut.cz/&lt;vase_uzivatelske_jmeno&gt; /BI-SQL

STRUKTURA DOKUMENTU:
   Odevzdaná práce (XML dokument) nechť je validní dle specifikace sprojekt. Na adrese:
   <link url="https://users.fit.cvut.cz/~halaska/BI-SQL/semestralka/sprojekt">https://users.fit.cvut.cz/~halaska/BI-SQL/semestralka/sprojekt/</link>
   najdete specifikace ve formátu DTD, XML Schema, Relax NG (sprojekt.dtd, sprojekt.xsd, sprojekt.png).
   Pro editaci práce tedy lze použít libovolný XML editor.
   Kompletní podpora pro formátování semestrálky (šablony a ukázkové semestrálky) 
   pro kompletní offline práci je:
<link url="http://users.fit.cvut.cz/~halaska/BI-SQL/semestralka/sprojekt.zip">http://users.fit.cvut.cz/~halaska/BI-SQL/semestralka/sprojekt.zip</link>

TVORBA DOKUMENTU (semestrálky)
   Pokud použijete jiný editor než XML Mind (viz níže), doporučuji stáhnout si šablonu pro semestrálku z SQL,
      <link url="https://users.fit.cvut.cz/~halaska/BI-SQL/semestralka/main.xml">https://users.fit.cvut.cz/~halaska/BI-SQL/semestralka/main.xml</link>
   tu otevřít a vyplnit vlastním textem vaší semestrální práce.
   Pokud toto neuděláte, pak je třeba, aby váš nově vytvořený dokument odkazoval na formátovací šablonu 
   pro zobrazení v html podobě. Za specifikaci kódování v XML souboru:
   &lt;?xml version="1.0" encoding="UTF-8"?&gt;
  je třeba umístit tuto instrukci pro provedení:
&lt;?xml-stylesheet type="text/xsl" href="hhttps://users.fit.cvut.cz/~halaska/BI-SQL/semestralka/sprojekt_html.xsl"?&gt;


EDITOR XML MIND - DOPORUČUJI PRO TVORBU SEMESTRÁLKY
Home Edition tohoto nástroje je volně ke stažení pro platformy linux i windows:
